<?php

namespace App\Services;

use App\Models\AtkDivisionStock;
use App\Models\AtkDivisionStockSetting;
use App\Models\AtkItem;
use App\Models\AtkStockRequest;
use App\Models\AtkStockRequestItem;
use App\Models\User;
use App\Models\UserDivision;
use Illuminate\Database\UniqueConstraintViolationException;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;

class StockRequestService
{
    protected $approvalService;

    public function __construct(ApprovalService $approvalService)
    {
        $this->approvalService = $approvalService;
    }

    /**
     * Create a new stock request
     *
     * @param  User  $user  The user creating the request
     * @param  array  $data  The request data
     */
    public function createStockRequest(User $user, array $data): AtkStockRequest
    {
        // Limits are enforced here, not only in the fan-out method, so no call
        // path can bypass them.
        $this->validateLimits([$data['division_id']], $data['items']);

        return $this->retryOnDuplicateRequestNumber(
            fn () => $this->createStockRequestOnce($user, $data)
        );
    }

    /**
     * Create a stock request in a single transaction.
     *
     * The request number is generated by StockRequestModelTrait (via
     * StockNumberGenerator), which locks per division to avoid collisions.
     * It must not be set here, or the trait's empty() guard skips generation.
     */
    protected function createStockRequestOnce(User $user, array $data): AtkStockRequest
    {
        return DB::transaction(function () use ($user, $data) {
            $stockRequest = new AtkStockRequest([
                'requester_id' => $user->id,
                'division_id' => $data['division_id'],
                'notes' => $data['notes'] ?? null,
            ]);

            if (isset($data['status'])) {
                $stockRequest->status = $data['status'];
            }

            $stockRequest->save();

            foreach ($data['items'] as $itemData) {
                $requestItem = new AtkStockRequestItem([
                    'item_id' => $itemData['item_id'],
                    'quantity' => $itemData['quantity'],
                ]);

                // category_id is NOT NULL, so fall back to the item's own category.
                $requestItem->category_id = $itemData['category_id']
                    ?? AtkItem::find($itemData['item_id'])?->category_id;

                $stockRequest->atkStockRequestItems()->save($requestItem);
            }

            // The trait's created hook also creates an approval; this call is
            // idempotent because createApproval() guards on an existing record.
            $this->approvalService->createApproval($stockRequest, 'AtkStockRequest');

            return $stockRequest;
        });
    }

    /**
     * Retry creation when two concurrent first-ever requests for the same
     * division compute the same number. lockForUpdate() cannot prevent this,
     * because locking an empty result set locks nothing.
     */
    protected function retryOnDuplicateRequestNumber(callable $create): AtkStockRequest
    {
        $attempts = 3;

        for ($attempt = 1; ; $attempt++) {
            try {
                return $create();
            } catch (UniqueConstraintViolationException $e) {
                if ($attempt >= $attempts) {
                    throw $e;
                }
            }
        }
    }

    /**
     * Create one single-division request per selected division, atomically.
     *
     * Each division gets its own request, its own copy of the items, and its
     * own approval flow, because stock, budget, and approvals are per division.
     * Authorization and limit checks run before the transaction so a rejection
     * cannot leave partial writes behind.
     *
     * @return array<int, AtkStockRequest>
     */
    public function createStockRequestsForDivisions(User $user, array $data): array
    {
        $divisionIds = array_values(array_unique($data['division_ids']));

        $this->authorizeDivisions($user, $divisionIds);
        $this->validateLimits($divisionIds, $data['items']);

        return DB::transaction(function () use ($user, $divisionIds, $data) {
            return array_map(fn (int $divisionId) => $this->createStockRequestOnce($user, [
                'division_id' => $divisionId,
                'status' => $data['status'] ?? null,
                'notes' => $data['notes'] ?? null,
                'items' => $data['items'],
            ]), $divisionIds);
        });
    }

    /**
     * Ensure the user may create requests for every selected division.
     *
     * DivisionScoped only guards reads; there is no write-side equivalent, so
     * without this a crafted payload could create requests in divisions the
     * user cannot even see.
     *
     * @param  array<int, int>  $divisionIds
     */
    protected function authorizeDivisions(User $user, array $divisionIds): void
    {
        if ($user->isSuperAdmin()) {
            return;
        }

        $allowed = $user->divisions()->pluck('user_divisions.id')->all();
        $forbidden = array_diff($divisionIds, $allowed);

        if ($forbidden !== []) {
            throw ValidationException::withMessages([
                'division_ids' => 'You are not assigned to division(s): '.implode(', ', $forbidden).'.',
            ]);
        }
    }

    /**
     * Reject quantities that would exceed a division's configured max limit.
     *
     * Limits are per division, so this cannot be checked once against a single
     * division. Requests are rejected rather than clamped: a request states
     * intent, so silently reducing the quantity would misrepresent the user.
     *
     * @param  array<int, int>  $divisionIds
     * @param  array<int, array<string, mixed>>  $items
     */
    protected function validateLimits(array $divisionIds, array $items): void
    {
        $errors = [];

        foreach ($divisionIds as $divisionId) {
            $division = UserDivision::find($divisionId);
            $divisionName = $division?->name ?? (string) $divisionId;

            foreach ($items as $item) {
                $itemId = $item['item_id'] ?? null;
                $quantity = (int) ($item['quantity'] ?? 0);

                if (! $itemId || $quantity <= 0) {
                    continue;
                }

                $setting = AtkDivisionStockSetting::where('division_id', $divisionId)
                    ->where('item_id', $itemId)
                    ->first();

                if (! $setting) {
                    continue; // No limit configured for this division/item.
                }

                $currentStock = (int) (AtkDivisionStock::where('division_id', $divisionId)
                    ->where('item_id', $itemId)
                    ->value('current_stock') ?? 0);

                $available = $setting->max_limit - $currentStock;

                if ($quantity > $available) {
                    $itemName = AtkItem::find($itemId)?->name ?? (string) $itemId;
                    $errors[] = "{$divisionName} / {$itemName}: requested {$quantity}, available {$available}.";
                }
            }
        }

        if ($errors !== []) {
            throw ValidationException::withMessages([
                'atkStockRequestItems' => 'Quantity exceeds the maximum limit — '.implode(' ', $errors),
            ]);
        }
    }

    /**
     * Approve a stock request
     *
     * @param  AtkStockRequest  $stockRequest  The stock request to approve
     * @param  User  $user  The user approving the request
     * @param  string|null  $notes  Optional notes
     * @return bool True if the approval is completed, false if there are more steps
     */
    public function approveStockRequest(AtkStockRequest $stockRequest, User $user, ?string $notes = null): bool
    {
        $approval = $stockRequest->approval;

        if (! $approval) {
            throw new \Exception('No approval found for this stock request');
        }

        // Process the approval step
        $isCompleted = $this->approvalService->processApprovalStep($approval, $user, 'approve', $notes);

        // If approval is completed, update the division stocks
        // NOTE: Stock updates are handled by StockUpdateService through the approval process
        // to ensure proper MAC calculations and other business logic
        if ($isCompleted && $approval->status === 'approved') {
            // $this->updateDivisionStocks($stockRequest); // COMMENTED OUT - DUPLICATE PROCESSING
        }

        return $isCompleted;
    }

    /**
     * Reject a stock request
     *
     * @param  AtkStockRequest  $stockRequest  The stock request to reject
     * @param  User  $user  The user rejecting the request
     * @param  string|null  $notes  Optional notes
     */
    public function rejectStockRequest(AtkStockRequest $stockRequest, User $user, ?string $notes = null): void
    {
        $approval = $stockRequest->approval;

        if (! $approval) {
            throw new \Exception('No approval found for this stock request');
        }

        // Process the rejection
        $this->approvalService->processApprovalStep($approval, $user, 'reject', $notes);
    }

    /**
     * Update division stocks when a stock request is approved
     * NOTE: This method is currently not used - stock updates are handled by StockUpdateService
     * This is kept for reference or future modifications
     *
     * @param  AtkStockRequest  $stockRequest  The approved stock request
     */
    protected function updateDivisionStocks(AtkStockRequest $stockRequest): void
    {
        foreach ($stockRequest->atkStockRequestItems as $requestItem) {
            // Find or create the division stock record
            $divisionStock = AtkDivisionStock::firstOrNew([
                'division_id' => $stockRequest->division_id,
                'item_id' => $requestItem->item_id,
            ]);

            // Update the quantity - NOTE: field name corrected from 'quantity' to 'current_stock'
            $divisionStock->current_stock += $requestItem->quantity;
            $divisionStock->save();
        }
    }

    /**
     * Cancel a stock request
     *
     * @param  AtkStockRequest  $stockRequest  The stock request to cancel
     * @param  User  $user  The user cancelling the request
     */
    public function cancelStockRequest(AtkStockRequest $stockRequest, User $user): void
    {
        $approval = $stockRequest->approval;

        if (! $approval) {
            throw new \Exception('No approval found for this stock request');
        }

        // Cancel the approval
        $this->approvalService->cancelApproval($approval, $user);
    }
}
